import { Users, TrendingUp, Search, UserPlus, CheckCircle } from 'lucide-react';
import { Card } from '../ui/card';
import { Button } from '../ui/button';
import { Input } from '../ui/input';
import { Badge } from '../ui/badge';
import { Avatar, AvatarFallback } from '../ui/avatar';
import { ImageWithFallback } from '../figma/ImageWithFallback';
import { useNavigate } from 'react-router-dom';

export function GroupsDiscovery() {
	const navigate = useNavigate();
	const myGroups = [
		{ id: 1, name: 'React Developers', members: 12543, posts: 1234, image: 'https://images.unsplash.com/photo-1566915896913-549d796d2166?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9ncmFtbWluZyUyMHdvcmtzcGFjZSUyMGRldmVsb3BlcnxlbnwxfHx8fDE3NjI3Mzg0MzV8MA&ixlib=rb-4.1.0&q=80&w=1080', joined: true },
		{ id: 2, name: 'System Design', members: 8932, posts: 892, image: 'https://images.unsplash.com/photo-1675495277087-10598bf7bcd1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb2RlJTIwYWxnb3JpdGhtJTIwdGVjaG5vbG9neXxlbnwxfHx8fDE3NjI3NTU3NjZ8MA&ixlib=rb-4.1.0&q=80&w=1080', joined: true }
	];
	const suggestedGroups = [
		{ id: 3, name: 'TypeScript Masters', members: 15234, posts: 2341, description: 'Advanced TypeScript patterns, best practices, and discussions', image: 'https://images.unsplash.com/photo-1587037325379-0b8807b41f23?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxvbmxpbmUlMjBsZWFybmluZyUyMGNsYXNzcm9vbXxlbnwxfHx8fDE3NjI3NTU3NjZ8MA&ixlib=rb-4.1.0&q=80&w=1080', category: 'Programming Languages', trending: true },
		{ id: 4, name: 'Algorithm Study Group', members: 21453, posts: 3456, description: 'Daily algorithm challenges and interview preparation', image: 'https://images.unsplash.com/photo-1675495277087-10598bf7bcd1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb2RlJTIwYWxnb3JpdGhtJTIwdGVjaG5vbG9neXxlbnwxfHx8fDE3NjI3NTU3NjZ8MA&ixlib=rb-4.1.0&q=80&w=1080', category: 'Data Structures & Algorithms', trending: true },
		{ id: 5, name: 'Web3 Developers', members: 9823, posts: 1567, description: 'Blockchain, smart contracts, and decentralized applications', image: 'https://images.unsplash.com/photo-1566915896913-549d796d2166?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9ncmFtbWluZyUyMHdvcmtzcGFjZSUyMGRldmVsb3BlcnxlbnwxfHx8fDE3NjI3Mzg0MzV8MA&ixlib=rb-4.1.0&q=80&w=1080', category: 'Emerging Tech', trending: false },
		{ id: 6, name: 'Python for Data Science', members: 18765, posts: 2890, description: 'ML, data analysis, and scientific computing with Python', image: 'https://images.unsplash.com/photo-1587037325379-0b8807b41f23?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxvbmxpbmUlMjBsZWFybmluZyUyMGNsYXNzcm9vbXxlbnwxfHx8fDE3NjI3NTU3NjZ8MA&ixlib=rb-4.1.0&q=80&w=1080', category: 'Data Science', trending: false },
		{ id: 7, name: 'DevOps & Cloud', members: 13421, posts: 1923, description: 'CI/CD, containerization, and cloud infrastructure', image: 'https://images.unsplash.com/photo-1739298061740-5ed03045b280?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0ZWFtJTIwY29sbGFib3JhdGlvbiUyMG9mZmljZXxlbnwxfHx8fDE3NjI2OTQ5Nzh8MA&ixlib=rb-4.1.0&q=80&w=1080', category: 'Infrastructure', trending: false },
		{ id: 8, name: 'Mobile Development', members: 16234, posts: 2134, description: 'iOS, Android, React Native, and Flutter discussions', image: 'https://images.unsplash.com/photo-1566915896913-549d796d2166?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9ncmFtbWluZyUyMHdvcmtzcGFjZSUyMGRldmVsb3BlcnxlbnwxfHx8fDE3NjI3Mzg0MzV8MA&ixlib=rb-4.1.0&q=80&w=1080', category: 'Mobile', trending: false }
	];

	return (
		<div className="max-w-7xl mx-auto px-6 py-8">
			<div className="mb-8"><h1 className="text-gray-900 mb-2">Groups</h1><p className="text-gray-600">Connect with learners and professionals who share your interests</p></div>
			<div className="flex items-center gap-4 mb-8"><div className="flex-1 relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" /><Input type="text" placeholder="Search groups..." className="pl-10 bg-white" /></div><Button variant="outline">All Categories</Button><Button variant="outline" className="gap-2"><TrendingUp className="w-4 h-4" />Trending</Button></div>
			{myGroups.length > 0 && (<div className="mb-8"><h2 className="text-gray-900 mb-4">My Groups</h2><div className="grid grid-cols-2 gap-6">{myGroups.map((group) => (<Card key={group.id} className="overflow-hidden hover:shadow-lg transition-shadow cursor-pointer" onClick={() => navigate('/groups/react-developers')}><div className="h-32 overflow-hidden"><ImageWithFallback src={group.image} alt={group.name} className="w-full h-full object-cover" /></div><div className="p-6"><div className="flex items-start justify-between mb-4"><div><h3 className="text-gray-900 mb-2">{group.name}</h3><div className="flex items-center gap-4 text-gray-500 text-sm"><div className="flex items-center gap-1"><Users className="w-4 h-4" /><span>{group.members.toLocaleString()} members</span></div><span>•</span><span>{group.posts.toLocaleString()} posts</span></div></div><CheckCircle className="w-5 h-5 text-green-500" /></div><Button variant="outline" className="w-full" onClick={(e) => { e.stopPropagation(); navigate('/groups/react-developers'); }}>View Group</Button></div></Card>))}</div></div>)}
			<div><h2 className="text-gray-900 mb-4">Suggested for You</h2><div className="grid grid-cols-3 gap-6">{suggestedGroups.map((group) => (<Card key={group.id} className="overflow-hidden hover:shadow-lg transition-shadow"><div className="h-40 overflow-hidden relative"><ImageWithFallback src={group.image} alt={group.name} className="w-full h-full object-cover" />{group.trending && (<Badge className="absolute top-3 right-3 bg-[#00BCD4] gap-1"><TrendingUp className="w-3 h-3" />Trending</Badge>)}</div><div className="p-6"><Badge variant="secondary" className="mb-3 bg-gray-100 text-gray-700">{group.category}</Badge><h3 className="text-gray-900 mb-2">{group.name}</h3><p className="text-gray-600 text-sm mb-4 line-clamp-2">{group.description}</p><div className="flex items-center gap-4 text-gray-500 text-sm mb-4"><div className="flex items-center gap-1"><Users className="w-4 h-4" /><span>{group.members.toLocaleString()}</span></div><span>•</span><span>{group.posts.toLocaleString()} posts</span></div><div className="flex items-center gap-3"><div className="flex -space-x-2">{[1, 2, 3].map((i) => (<Avatar key={i} className="border-2 border-white w-8 h-8"><AvatarFallback className="bg-[#1A237E] text-white text-xs">U{i}</AvatarFallback></Avatar>))}</div><span className="text-gray-500 text-sm">+{(group.members - 3).toLocaleString()} members</span></div><Button className="w-full mt-4 bg-[#00BCD4] hover:bg-[#00ACC1] text-white gap-2"><UserPlus className="w-4 h-4" />Join Group</Button></div></Card>))}</div></div>
		</div>
	);
}